version: '3.1'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postgresdb
  adminer:
    image: adminer
    ports:
      - 9001:8080