server:
  port: 8080
  servlet:
    context-path: /
springdoc:
  swagger-ui:
    oauth:
      client-id: clientId
      client-secret: clientSecret
    display-request-duration: true
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha

app:
  security:
    token:
      role:
        structure:
          # Insert Role JWT JSON Object Structure

# This structure is the JWT JSON Object which contains the roles
# The example below indicates a structure like {...,"resource_access":{"login":{ "roles": ['role1','role2']}}}
#          resource_access:
#            login:
#              roles: list
#
# At the moment, at the end of the structure you must select the type of object which contains roles
# It should be 'list' (see example above) or 'value' in case there was one role only
# Other types will throw an error

spring:
  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: # insert issuer uri
          jwk-set-uri: # Insert cert uri
# Example
#
# Keycloak
#          issuer-uri: https://localhost:8090/auth/realms/<realmName>
#          jwk-set-uri: https://localhost:8090/auth/realms/<realmName>/protocol/openid-connect/certs
# Authentik
#          issuer-uri: http://localhost:8090/application/o/<appName>/
#          jwt-set-uri: http://localhost:8090/application/o/<appName>/jwks/