
spring.application.name: grid-webflux-service2
springfox.documentation.swagger.v2.path: /grid-webflux-service2

server:
   port: 8081
   servlet.context-path: /
   
springdoc:
  swagger-ui:
    oauth:
      tokenURL: url
      client-id: clientId
      client-secret: clientSecret
    display-request-duration: true
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha

service2:
  consumers:
    service1:
      baseUrl: http://localhost:8080
      paths:
        messages: /v1/messages/